<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <RootNamespace>BinanceFixMarketdataConnector</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
        <PackageReference Include="QuickFIXn.Core" Version="1.14.0" />
        <PackageReference Include="QuickFIXn.FIX44" Version="1.14.0"/>
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.0" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.0" />
        <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="9.0.0" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.0" />
        <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.0" />
    </ItemGroup>

    <ItemGroup>
        <None Update="config/settings.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="config/fix_config.cfg">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="config/binance-spot-fix-md.xml">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="keys/private.ed25519.pem">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="keys/api.key">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="LICENSE">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
          <Link>LICENSE</Link>
        </None>
        <None Update="LICENSE.QuickFIX">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
          <Link>LICENSE.QuickFIX.txt</Link>
        </None>
    </ItemGroup>
</Project>